# Generated by Django 6.0.7 on 2026-07-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
