# Generated by Django 5.1.15 on 2026-07-09 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='product.product'),
        ),
    ]
