# Generated by Django 6.0.7 on 2026-07-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_banner_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='dateFrom',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='dateTo',
            field=models.CharField(max_length=5),
        ),
    ]
