# Generated by Django 5.1.15 on 2026-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productpreview_preview_productreviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isLimited',
            field=models.BooleanField(default=False),
        ),
    ]
