# Generated by Django 5.1.15 on 2026-07-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_catalogpreview_alter_category_image_and_more'),
        ('product', '0003_product_islimited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='catalog.subcategory'),
        ),
    ]
