# Generated by Django 5.1.15 on 2026-07-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category_alter_productreviews_date_and_more'),
        ('user_profile', '0004_alter_profileavatar_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='author',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_profile.profile'),
            preserve_default=False,
        ),
    ]
