# Generated by Django 5.1.15 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productreviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
