# Generated by Django 5.1.15 on 2026-07-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_catalogpreview_date'),
        ('product', '0007_alter_productreviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='catalog.subcategory'),
        ),
    ]
