# Generated by Django 5.1.15 on 2026-07-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('pk',)},
        ),
    ]
