# Generated by Django 5.1.15 on 2026-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatar',
            name='preview',
            field=models.ImageField(upload_to=''),
        ),
    ]
