# Generated by Django 5.1.15 on 2026-07-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_profileavatar_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileavatar',
            name='preview',
            field=models.ImageField(upload_to='user_avatar'),
        ),
    ]
