# Generated by Django 5.1.15 on 2026-07-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypreview',
            name='preview',
            field=models.ImageField(upload_to='category_preview/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategorypreview',
            name='preview',
            field=models.ImageField(upload_to='subcategory_preview/'),
        ),
    ]
