# Generated by Django 5.1.15 on 2026-07-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_tag_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
