# Generated by Django 5.1.15 on 2026-07-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basket_product'),
        ('catalog', '0003_remove_product_category_remove_product_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
