# Generated by Django 5.1.15 on 2026-07-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_product_delete_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='catalog_preview/')),
                ('alt', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogpreview'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogpreview'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
