# Generated by Django 5.1.15 on 2026-07-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_catalogpreview_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogpreview',
            name='date',
        ),
    ]
