# Generated by Django 5.1.15 on 2026-07-13 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('paymentType', models.CharField(max_length=50)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('deliveryType', models.CharField(max_length=50)),
                ('products', models.ManyToManyField(related_name='order_products', to='product.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_profile', to='user_profile.profile')),
            ],
        ),
    ]
